# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

permissions:
  contents: write 
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Git config 
      run: |
        git config --global user.name "noyafx"
        git config --global user.email "111561391+noyafx@users.noreply.github.com"
        git submodule add https://$TOKEN@github.com/noyafx/database.git database 
        cd database && git remote set-url origin https://noyafx:$TOKEN@github.com/noyafx/database.git && cd ..
      env:
        TOKEN: ${{ secrets.GH_PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run script
      run: npm i && npm run start
      env:
        TOKEN: ${{ secrets.GH_PAT }}
    - name: Cache save
      if: ${{ always() }}
      run: cd database && git add . && git commit -m "database update" && git push origin
