# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      npm-script:
        description: npm script to run(*´ω｀*)
        type: string
        required: true
        default: 'start'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Git config 
      run: |
        git config --global user.name "noyafx"
        git config --global user.email "111561391+noyafx@users.noreply.github.com"
      env:
        TOKEN: ${{ secrets.GH_PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run script
      id: run-script
      run: npm run ${{ inputs.npm-script }}
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TOKEN: ${{ secrets.GH_PAT }}
    - name: Cache save
      if: ${{ always() && (inputs.npm-script == 'start') }}
      run: cd database && git add . && git commit -m "database update" && git push origin
    - name: Continue workflow
      if: ${{ (steps.run-script.conclusion == 'success') && (inputs.npm-script == 'start') }}
      run: curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/noyafx/noya/actions/workflows/node.yml/dispatches -d '{"ref":"main","inputs":{}}'
      env:
        TOKEN: ${{ secrets.GH_PAT }}
